### ISSUE TITLE
How could I send multiple push notifications ? 

### ISSUE THREAD

**Issue by Wanty** [richsage/RMSPushNotificationsBundle#95]
Hello,

I have a function (sendPushNotifications) in my controller which send multiple push notifications and then return a Response object.

- My (huge) problem : before returning the Response object, my "sendPushNotifications" function wait until all push notifications are sent.

- My question : how can I return the Response object AND THEN send all push notifications ?

Kind regards,
Wanty

**Comment by richsage** [comment]
One way would be to register an event listener on the `kernel.terminate` event, and send your notifications there (since this event is triggered when the kernel is shutting down, after a response has been sent).

You could also shift these notifications into some kind of process queue and handle them in the background (cron task, queue eg rabbitmq and similar).

There are a few options :-)

**Comment by Wanty** [comment]
Hello @richsage,
Thank you for your comment.

I would like to register an event listener on the kernel.terminate event (as you said before) for the following function "public function sendPushNotificationsAction() { ... return new Response() }" : how should I proceed ?

Thank you in advance,
Wanty

**Comment by richsage** [comment]
You might want to take a look at the Symfony docs for the [kernel.terminate](http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-terminate-event) event
